name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Build
        run: |
          go build -o terraform-provider-slack_v${{ github.ref_name }}
          GOOS=linux GOARCH=amd64 go build -o terraform-provider-slack_v${{ github.ref_name }}_linux_amd64
          GOOS=windows GOARCH=amd64 go build -o terraform-provider-slack_v${{ github.ref_name }}_windows_amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o terraform-provider-slack_v${{ github.ref_name }}_darwin_amd64
      - name: Package
        run: |
          zip terraform-provider-slack_v${{ github.ref_name }}_linux_amd64.zip terraform-provider-slack_v${{ github.ref_name }}_linux_amd64
          zip terraform-provider-slack_v${{ github.ref_name }}_windows_amd64.zip terraform-provider-slack_v${{ github.ref_name }}_windows_amd64.exe
          zip terraform-provider-slack_v${{ github.ref_name }}_darwin_amd64.zip terraform-provider-slack_v${{ github.ref_name }}_darwin_amd64
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/git @semantic-release/github
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
